#ifndef _ERRORS_H
#define _ERRORS_H

enum GENERAL_ERROR_CODE {
    SUCCESS = 0,
    MEMORY_ERROR = -1,
    ACCESS_ERROR = -2,
    OPEN_ERROR = -3,
    READ_ERROR = -4,
    SEEK_ERROR = -5,
    WRITE_ERROR = -6,
};

enum CHUNK_ERROR_CODE {
    INSUFFICIENT_SPACE_FOR_CHUNK = -10,
    CHUNK_NOT_PRESENT = -11,
    INVALID_HEADER = -12,
};

enum COMPRESSION_ERROR_CODE {
    ZLIB_STREAM_INIT_ERROR = -20,
    ZLIB_INFLATE_ERROR = -21,
    ZLIB_STREAM_FREE_ERROR = -22,
    ZLIB_DEFLATE_ERROR = -23
};

#endif